#!/usr/bin/env bash
# Configures Nginx to include a custom HTTP response header `X-Served-By` with the server hostname

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to include the custom header
sudo bash -c 'echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        add_header X-Served-By \$hostname;
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default'

# Reload or restart Nginx
sudo systemctl reload nginx
sudo systemctl restart nginx
