#!/usr/bin/env bash
cript to double the number of web servers and add new configurations
# Update and install Nginx

echo "Updating package list and installing Nginx..."
sudo apt-get update && sudo apt-get -y install nginx

# Add custom header to nginx configuration
echo "Adding custom configuration to Nginx..."
config_line="add_header X-Served-By \"\$HOSTNAME\";"
sudo sed -i "/http {/a \\t$config_line" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
echo "Restarting Nginx to apply the new configuration..."
sudo service nginx restart

echo "Nginx setup complete with updated configuration."
