#!/usr/bin/env bash
# This script sets up the server to listen on port 80 for all active IPv4 addresses
# Link the default configuration file to sites-enabled
# Restart the Nginx service to apply the changes
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
sudo service nginx restart
